name: ci

on:
  push:
    # branches:
    #   - master
    tags:
      - "v*"
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Theos Setup
        uses: Randomblock1/theos-action@v1

      - name: Build shadow
        run: ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ${{ github.workspace }}/packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}